document.write('<h1>КОНСТАНТИ</h1>');
document.write('Значення константи е = ' + Math.E + '<BR>');
document.write('Значення константи π = ' + Math.PI + '<BR>');
document.write('Десятковий логарифм постійної Ейлера (е) = ' + Math.LOG10E + '<BR>');
document.write('Двійковий логарифм постійної Ейлера (е) = ' + Math.LOG2E + '<BR>');
document.write('Натуральний логарифм числа 10 = ' + Math.LN10 + '<BR>');
document.write('Натуральний логарифм числа 2 = ' + Math.LN2 + '<BR>');
document.write('Корінь квадратний із двох = ' + Math.SQRT2 + '<BR>');
document.write('Корінь квадратний з однієї другий = ' + Math.SQRT1_2 + '<BR>');
document.write('<h1>ФУНКЦІЇ</h1>');
document.write('Результат добування квадратного кореня з 4: y = ' + Math.sqrt(4) + '<BR>');
document.write('Результат добування квадратного кореня з -9: y = ' + Math.sqrt(-9) + '<BR>');
document.write('Результат обчислення абсолютного значення -9: y = ' + Math.abs(-9) + '<BR>');
document.write('Результат обчислення косинуса нуля радіан: y = ' + Math.cos(0) + '<BR>');
document.write('Косинус 180 градусів (π радіан): y = ' + Math.cos(Math.PI) + '<BR>');
document.write('Результат обчислення арккосинуса нуля : y = ' + Math.acos(0) + '<BR>');
document.write('Результат обчислення синуса нуля радіан: y = ' + Math.sin(0) + '<BR>');
document.write('Синус 90 градусів (π /2 радіан): y = ' + Math.sin(Math.PI / 2) + '<BR>');
document.write('Результат обчислення арксинуса одиниці: y = ' + Math.asin(1) + '<BR>');
document.write('Тангенс 45 градусів (π /4 радіан): y = '+ Math.tan(Math.PI / 4) + '<BR>');
document.write('Результат обчислення арктангенса одиниці: y = '+ Math.atan(1) + '<BR>');
document.write('Результат зведення е в ступінь 2: y = '+ Math.pow(Math.E, 2) + '<BR>');
document.write('Натуральний логарифм від e2: y = '+ Math.log(Math.pow(Math.E, 2)) + '<BR>');
document.write('Результат обчислення десяткового логарифма від числа 100: y = ', Math.log10(100) + '<BR>');
document.write('Результат обчислення двійкового логарифма від числа 8: y = ', Math.log2(8) + '<BR>');
document.write('Тангенс 45 градусів (з округленням): y = ', Math.round(Math.tan(Math.PI / 4)) + '<BR>');
document.write('Результат округлення числа 1,00123 у більшу сторону: y = '  + Math.ceil(1.00123) + '<BR>');
document.write('Результат округлення числа -3.1234 у більшу сторону: y = '+ Math.ceil(-3.1234) + '<BR>');
document.write('Результат округлення числа 1,00123 у меншу сторону: y = ' + Math.floor(1.00123) + '<BR>');
document.write('Результат округлення числа -3.1234 у меншу сторону: y = ' + Math.floor(-3.1234) + '<BR>');
document.write('Результат округлення числа 1,44 за правилами арифметики: y = ' + Math.round(1.44) + '<BR>');
document.write('Результат округлення числа 1,54 за правилами арифметики: y = ' + Math.round(1.54) + '<BR>');
document.write('Вибір найбільшого із двох чисел 4 й 2: y = ' + Math.max(4,2) + '<BR>');
document.write('Вибір найменшого із двох чисел 4 й 2: y = ' + Math.min(4,2) + '<BR>');
document.write('<h1>ГЕНЕРАТОР ВИПАДКОВИХ ЧИСЕЛ</h1>');
document.write('Формування випадкових чисел в інтервалі [0;1]: y = ' + Math.random(0, 1) + '<BR>');